### ISSUE TITLE
LittleBigPlanet fonts are broken and LBP v2 does not exist

### ISSUE THREAD

**Issue by Teslahaha** [Mondanzo/BD#1]
![](https://i.imgur.com/8Y1upr8.jpg)

**Comment by Mondanzo** [comment]
I have no clue what you mean with LBP v2.
About the font I'm gonna try to fix it by importing the font from the internet instead of using base64... will just need a new option for BDv2 then..

**Comment by Teslahaha** [comment]
I heard there was a v2 of the skin somewhere but I forgot. But thanks!
